apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o45u4xnvu-go
  janus-idp.io/tekton: o45u4xnvu-go
  backstage.io/kubernetes-id: o45u4xnvu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o45u4xnvu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
